# Generated by Django 3.0.7 on 2020-06-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200629_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(upload_to='blog/posts'),
        ),
    ]
