# Generated by Django 3.0.7 on 2020-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200629_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.FileField(blank=True, upload_to='blog/posts'),
        ),
    ]
